### ISSUE TITLE
How do I submit an answer?

### ISSUE THREAD

**Issue by 1x6** [theusaf/KahootPY#2]
pls answer kthx

**Comment by theusaf** [comment]
Use the [`answerQuestion`](https://github.com/theusaf/KahootPY/blob/master/Documentation.md#kahoot.methods.answerQuestion) function.
Example:
```py
from kahoot import client
bot = client()
bot.join(12345,"KahootPY")
def questionStartHandle(q):
  bot.answerQuestion(0)
  # q.answer(0) also works
bot.on("questionStart",questionStartHandle)
```

The documentation is taken from kahoot.js-updated (v1) as this project is based on kahoot.js-updated, which is why it says "returns Promise" (doesn't actually return anything)
